"""add saved_charts table

Revision ID: 776613fc9fe2
Revises: a864e19f8035
Create Date: 2026-07-30 17:41:46.481522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776613fc9fe2'
down_revision = 'a864e19f8035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_charts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chart_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_charts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_charts_user_id'))

    op.drop_table('saved_charts')
    # ### end Alembic commands ###
